### ISSUE TITLE
Does not work with SBT 0.13.5

### ISSUE THREAD

**Issue by hf** [sbt/sbt-protobuf#21]
Instructions to enable do not work on SBT 0.13.5.

**Comment by jnfeinstein** [comment]
I can't get it to work either.  Could you post an example configuration with a few of the settings?  The only thing I found was from 2011 and that isn't working.

**Comment by jnfeinstein** [comment]
```scala
sourceDirectories in PB.protobufConfig <+= (externalIncludePath in PB.protobufConfig).identity
```
Possibly `.identity()` was changed?

**Comment by xuwei-k** [comment]
> This doesn't work. Possibly .identity() was changed?

fixed https://github.com/sbt/sbt-protobuf/commit/c64aba8262a5cce6d446
