### ISSUE TITLE
Don't rely on protoc executable

### ISSUE THREAD

**Issue by copumpkin** [sbt/sbt-protobuf#23]
It'd be nice for these projects to be as self-contained as possible, and relying on an environment protoc seems unfortunate when we're already explicitly depending on the protocol buffers maven package. I don't know if there's a clean way to generate source from a library, but a silent dependency makes me sad.

**Comment by gseitz** [comment]
@copumpkin: In case you're still using sbt-protobuf, I just published `0.4.0` with a new `TaskKey[Seq[String] => Int]` called `runProtoc` which you can set to `args => com.github.os72.protocjar.Protoc.runProtoc(args)` to invoke the protobuf compiler coming from a downloaded dependent artifact (granted that the build has a dependency on the correct protoc-jar version).

**Comment by gseitz** [comment]
Fixed by 779c6ee32486890c327207efff58a05858a178c3.
