### ISSUE TITLE
Add gRPC/protobuf3 support.

### ISSUE THREAD

**Issue by aloiscochard** [sbt/sbt-protobuf#31]
It's actually purely config, but that would be nice to have some facilities, I suppose we could get `java_rpc_out` and `plugin` value generated behind a gRPC flag or something.

Here is the hacked config I have in my toy project at the moment:

```
      version in protobufConfig := "3.0.0-alpha-3.1",
      protocOptions in protobufConfig ++= Seq(
        "--plugin=protoc-gen-java_rpc=/usr/local/bin/protoc-gen-grpc-java",
        "--java_rpc_out=examples/target/scala-2.11/src_managed/main/compiled_protobuf"
      )
```

What do you think?

**Comment by xuwei-k** [comment]
FYI
- https://github.com/trueaccord/ScalaPB/issues/44
- https://github.com/xuwei-k/grpc-scala-sample

**Comment by vach** [comment]
@aloiscochard can this be modified to use grpc jar from repo instead of local binary?

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/sbt/sbt-protobuf/pull/177
