### ISSUE TITLE
version setting not working?

### ISSUE THREAD

**Issue by pcleary00** [sbt/sbt-protobuf#32]
I am trying to use version 0.4.0 of the plugin.

I have protoc version 2.4.1 installed locally.

I have tried modifying the version setting in my build file:

Seq(PB.protobufSettings: _*)

version in PB.protobufConfig := "2.4.1"

But it still pulls in protobuf-java 2.5.0

I am getting this issue when I try to use the generated protobuf classes:

```java.lang.UnsupportedOperationException: This is supposed to be overridden by subclasses.
[info]   at com.google.protobuf.GeneratedMessage.getUnknownFields(GeneratedMessage.java:180)```

I am trying to use the protobuf-java 2.4.1 library to no avail.

I really cannot update the protoc locally at this point.

Any pointers?

**Comment by pcleary00** [comment]
Nevermind, it turns out that 2.4.1 was being evicted by akka persistence :/

**Comment by ktoso** [comment]
Hi @pcleary00, I noticed this ticket and thought you may be happy to hear we're shimming protobuf in Akka 2.4.x now, so it will not pull in a protobuf dependency and you can use the version you want. :-)
