### ISSUE TITLE
Support compiling test protobufs

### ISSUE THREAD

**Issue by jdve** [sbt/sbt-protobuf#39]
I have some `*.proto` files that I use exclusively for testing kept under `src/test/resources`.  If I change `sourceDirectory` then the compiled classes get included in my final jar file.  I really only want these for testing, so they shouldn't be included in the final jar.  Any suggestion for how to workaround this problem?  Or maybe `sbt-protobuf` could support the `Test` configuration?

**Comment by jypma** [comment]
@jdve did you ever figure this out? I'm looking for a way as well.

**Comment by jdve** [comment]
Sorry, no I haven't.  I haven't had time to update sbt-protobuf either.

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt-protobuf/pull/43
