### ISSUE TITLE
"Protoc" can't be found

### ISSUE THREAD

**Issue by mbesida** [sbt/sbt-protobuf#44]
added plugin to plugins.sbt, added protbuf settings to the project. when I run next command protobuf:protobufGenerate  I get next error
_error occurred while compiling protobuf files: Cannot run program "protoc": CreateProcess error=2, The system cannot find the file specified

PS. runnig on windows

**Comment by sirthias** [comment]
You probably don't have `protoc` available in your environment.

This should get you going:

1. Add this line to your `plugins.sbt`:

```scala
libraryDependencies += "com.github.os72" % "protoc-jar" % "3.2.0.1"
```

2. Add this project setting to your build (in addition to the `ProtobufPlugin.protobufSettings`):

```scala
ProtobufPlugin.runProtoc in ProtobufPlugin.protobufConfig := (args =>
  com.github.os72.protocjar.Protoc.runProtoc("-v320" +: args.toArray))
```

**Comment by AceHack** [comment]
This does not work for me, any help is appreciated
