### ISSUE TITLE
integrate protobuf-scala

### ISSUE THREAD

**Issue by alexy** [sbt/sbt-protobuf#5]
Just found this: http://code.google.com/p/protobuf-scala/ -- perhaps better generate Scala instead of Java?  :)

**Comment by xuwei-k** [comment]
sbt-protobuf is a simple plugin for generate `.java` codes. Furthermore, I think http://code.google.com/p/protobuf-scala/ is not active project.
There are some another sbt-plugins for generate Scala codes.
- https://github.com/trueaccord/sbt-scalapb
- https://github.com/sbt/sbt-scalabuff
