### ISSUE TITLE
Support downloading protoc as an artifact

### ISSUE THREAD

**Issue by alenkacz** [sbt/sbt-protobuf#53]
Protoc is uploaded to maven repository so it can be added as dependency and resolved without the need of user having it installed. It would be nice to have this feature as a part of this plugin.

Google's gradle plugin is already doing this https://github.com/google/protobuf-gradle-plugin/blob/54ee5dbbf30c8f3667ec93e3730f18807b78e56f/src/main/groovy/com/google/protobuf/gradle/ExecutableLocator.groovy#L39

If you agree, I will be happy to work on this feature... @xuwei-k

**Comment by xuwei-k** [comment]
[protc-jar](https://github.com/os72/protoc-jar/tree/v3.5.1.1) has download feature

> download by maven artifact id: `-v:<group>:<artifact>:<version>` (eg, -v:com.google.protobuf:protoc:3.0.0)

**Comment by eed3si9n** [comment]
Hello from 2020. I think it would be great to have `protoc` downloading feature so we're not dependent on the local environment.

Regarding @xuwei-k's comment, I read it as a reference of a prior work that already does similar thing, which we can either use or get the inspiration for the implementation.

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/sbt/sbt-protobuf/pull/67
