### ISSUE TITLE
publish to maven central instead of bintray

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt-protobuf#73]
use `com.github.sbt` ? 🤔 👀 

- https://github.com/sbt/sbt/issues/6294
- https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
- https://github.com/sbt/sbt-release/issues/271

/cc @eed3si9n

**Comment by eed3si9n** [comment]
That's fine, but could you send PRs (and merge it yourself) so I'd know what changes are being made?

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt-protobuf/pull/74

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt-protobuf/releases/tag/v0.7.0
