### ISSUE TITLE
add `protobufExcludePaths` setting key

### ISSUE THREAD

**Issue by clairemcginty** [sbt/sbt-protobuf#98]
It would be helpful to have a `protobufExcludePaths` setting key. Example use case: excluding conflicting schema definitions from multiple external sources. The granularity would probably be best at the individual file level (not directory). happy to contribute this if others are in favor of this feature!

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/sbt/sbt-protobuf/pull/175
